### ISSUE TITLE
Ls PATH returns Type Error

### ISSUE THREAD

**Issue by RaghavRao** [pschmitt/pkp#25]
I might be using path wrong.

Usage:

`pkp -f db_path -F keyfile p password ls "My Passwords/Core" `

Error:

```

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.local/bin/pkp", line 8, in <module>
    sys.exit(cli_main())
  File "/data/data/com.termux/files/home/.local/pipx/venvs/pkp/lib/python3.9/site-packages/pkp.py", line 313, in cli_main
    sys.exit(main())
  File "/data/data/com.termux/files/home/.local/pipx/venvs/pkp/lib/python3.9/site-packages/pkp.py", line 301, in main
    return ls(kp, args)
  File "/data/data/com.termux/files/home/.local/pipx/venvs/pkp/lib/python3.9/site-packages/pkp.py", line 165, in ls
    entries = [x for x in entries if re.match(regex_path, x.path)]
  File "/data/data/com.termux/files/home/.local/pipx/venvs/pkp/lib/python3.9/site-packages/pkp.py", line 165, in <listcomp>
    entries = [x for x in entries if re.match(regex_path, x.path)]
  File "/data/data/com.termux/files/usr/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

```

**Comment by pschmitt** [comment]
Greeting, fellow Termux user!

There seems to be something wrong with pkp here, rather than your command. I will look into it. Thanks for reporting!
